# MIT 18.06SC — Lecture 2: Gaussian Elimination Exercise

Implement Gaussian elimination from scratch to solve linear systems $Ax = b$.

## Setup
Import necessary libraries.

In [ ]:
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

print("✓ Setup complete")

## Exercise: Implement Gaussian Elimination

Implement a function that solves $Ax = b$ using Gaussian elimination.

**Algorithm**:
1. **Forward Elimination**: Transform $A$ into upper triangular form $U$
   - For each column $j$ from 0 to $n-1$:
     - Pivot = $A[j, j]$
     - For each row $i$ below pivot ($i > j$):
       - Compute multiplier: $m_{ij} = A[i, j] / \text{pivot}$
       - Row operation: $A[i, :] = A[i, :] - m_{ij} \cdot A[j, :]$
       - Update RHS: $b[i] = b[i] - m_{ij} \cdot b[j]$

2. **Back Substitution**: Solve $Ux = c$ from bottom to top
   - Start from last row: $x[n-1] = c[n-1] / U[n-1, n-1]$
   - For each row $i$ from $n-2$ down to $0$:
     - $x[i] = (c[i] - \sum_{j=i+1}^{n-1} U[i,j] \cdot x[j]) / U[i,i]$

In [7]:
from curses import A_COLOR


def gaussian_elimination(A, b):
    """
    Solve the linear system Ax = b using Gaussian elimination.
    
    Parameters:
    -----------
    A : numpy.ndarray, shape (n, n)
        Coefficient matrix
    b : numpy.ndarray, shape (n,)
        Right-hand side vector
    
    Returns:
    --------
    x : numpy.ndarray, shape (n,)
        Solution vector
    """
    # TODO: Implement Gaussian elimination
    A_copy = A.copy()
    b_copy = b.copy()

    rows,cols = A.shape
    assert rows == cols, "Matrix must be square"
    
    for i in range(rows-1):
        multiplier = A_copy[i+1:,i]/A_copy[i,i]
        for index,m in enumerate(multiplier):
            A_copy[i+1+index] = A_copy[i+1+index] - m * A_copy[i]
            assert A_copy[i+1+index,i] == 0, "Upper triangular matrix expected"
            b_copy[i+1+index] = b_copy[i+1+index] - m * b_copy[i]

    U = A_copy
    print("Upper triangular matrix:")
    print(U)
    # Now our matrix is upper triangular
    # Solve for x from bottom to top
    x = np.zeros(rows)
    for i in range(rows-1, -1, -1):
        x[i] = (b_copy[i] - np.dot(A_copy[i][i+1:], x[i+1:])) / A_copy[i][i]

    return x

    

print("✓ Function defined")

✓ Function defined


## Test: Compare with NumPy

Test on the system from the lecture:
$$\begin{cases}
2u + v + w = 5 \\
4u - 6v = -2 \\
-2u + 7v + 2w = 9
\end{cases}$$

Expected solution: $u = 1, v = 1, w = 2$

In [8]:
# Define the system from lecture
A = np.array([
    [2, 1, 1],
    [4, -6, 0],
    [-2, 7, 2]
], dtype=float)

b = np.array([5, -2, 9], dtype=float)

print("System to solve:")
print("A =")
print(A)
print("\nb =")
print(b)

# Solve using our implementation
x_our = gaussian_elimination(A, b)

# Solve using NumPy
x_numpy = np.linalg.solve(A, b)

# Compare results
print("\n" + "=" * 60)
print("Results:")
print("=" * 60)
print(f"Our implementation:      x = {x_our}")
print(f"NumPy (np.linalg.solve): x = {x_numpy}")
print("=" * 60)

# Verify solution
residual_our = np.linalg.norm(A @ x_our - b)
residual_numpy = np.linalg.norm(A @ x_numpy - b)

print(f"\nResidual (our):   ||Ax - b|| = {residual_our:.2e}")
print(f"Residual (NumPy): ||Ax - b|| = {residual_numpy:.2e}")

# Check difference
difference = np.linalg.norm(x_our - x_numpy)
print(f"\nDifference: ||x_our - x_numpy|| = {difference:.2e}")

if difference < 1e-10:
    print("\n✅ Solutions match! Implementation is correct.")
else:
    print("\n❌ Solutions differ. Check implementation.")

System to solve:
A =
[[ 2.  1.  1.]
 [ 4. -6.  0.]
 [-2.  7.  2.]]

b =
[ 5. -2.  9.]
Upper triangular matrix:
[[ 2.  1.  1.]
 [ 0. -8. -2.]
 [ 0.  0.  1.]]

Results:
Our implementation:      x = [1. 1. 2.]
NumPy (np.linalg.solve): x = [1. 1. 2.]

Residual (our):   ||Ax - b|| = 0.00e+00
Residual (NumPy): ||Ax - b|| = 0.00e+00

Difference: ||x_our - x_numpy|| = 0.00e+00

✅ Solutions match! Implementation is correct.


## Visualize Upper Triangular Matrix

Test on a larger 10×10 system to see the upper triangular structure.

In [ ]:
# Create a 10x10 random system
np.random.seed(123)
A_large = np.random.randn(10, 10)
b_large = np.random.randn(10)

print("Original 10×10 matrix A:")
print(A_large)
print("\n" + "=" * 70)

# Solve using our implementation
x_large = gaussian_elimination(A_large, b_large)

print("=" * 70)
print("\n✓ Upper triangular structure achieved!")