# Chapter 2 Recap: Linear Algebra Essentials

Use this notebook to revisit the key linear algebra concepts underpinning deep learning. Complete each prompt before checking references or solutions elsewhere.

## Study Workflow
1. Read the question carefully and recall the underlying definitions.
2. Work through the algebra by hand or in the scratch cells.
3. (Optional) Verify numerically with NumPy once you have an answer.
4. Record insights, confusions, or follow-up topics in the reflection section.

In [1]:
import numpy as np  # Optional helper for numerical checks

np.set_printoptions(suppress=True)

## Part A. Basic Objects & Operations
Scalars, vectors, matrices, and tensors form the building blocks for deep learning models.

### 1. Basic Objects
Provide one example each of:
- A scalar (shape `()`),
- A vector (shape `(n,)`),
- A matrix (shape `(m, n)`),
- A 3rd-order tensor (shape `(d_1, d_2, d_3)`).

Note the values and their shapes.

In [2]:
# TODO: define your scalar, vector, matrix, and tensor examples
scalar = 1
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2], [3, 4]])
tensor3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# print scalar and shapes to confirm
print(scalar)
print(vector.shape)
print(matrix.shape)
print(tensor3.shape)


1
(3,)
(2, 2)
(2, 2, 2)


### 2. Vector Operations
Given $x = [1, 2, 3]$ and $y = [4, 5, 6]$, compute:
1. $x + y$
2. $2x - y$
3. $x \cdot y$ (dot product)


In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# TODO: replace the ellipses with your computations
# print('x + y =', ... )
# print('2x - y =', ... )
# print('x dot y =', ... )

print('x+y=',x+y)
print('2x-y=',2*x-y)
print('x dot y=',x@y)



x+y= [5 7 9]
2x-y= [-2 -1  0]
x dot y= 32


### Knowledge Key Point — Dot Product and Angle

For any non-zero vectors $\mathbf{a}$ and $\mathbf{b}$,

$\mathbf{a}\cdot\mathbf{b} = \|\mathbf{a}\|\,\|\mathbf{b}\| \cos\theta$

where $\theta$ is the angle between them. If the vectors are perpendicular, then $\theta = 90^\circ$, so $\cos\theta = 0$ and the dot product is zero.

### Exercise (TODO)

Pick two non-zero vectors in $\mathbb{R}^2$ or $\mathbb{R}^3$ that are perpendicular. Verify numerically that their dot product is zero and that the cosine formula above also evaluates to zero.


In [15]:
v1=np.array([1,1])
v2=np.array([-1,1])
np.dot(v1,v2)

np.int64(0)

### 3. Matrix Operations
For $A = \begin{bmatrix}1 & 2 \\ 3 & 4\end{bmatrix}$ and $B = \begin{bmatrix}2 & 0 \\ 1 & 2\end{bmatrix}$, determine:
1. $A + B$
2. $AB$
3. $A^\top$ (transpose)


In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

# TODO: compute the requested matrix expressions
print('A + B =\n', A+B )
print('A @ B =\n', A@B )
print('A^T =\n', np.transpose(A) )


A + B =
 [[3 2]
 [4 6]]
A @ B =
 [[ 4  4]
 [10  8]]
A^T =
 [[1 3]
 [2 4]]


## Part B. Matrix Properties
Determinants and inverses reveal how linear transformations scale or distort space.

### 4. Identity and Inverse
1. Write the $2\times2$ identity matrix $I$.
2. Compute $\det(A)$ to determine whether $A$ is invertible.
3. If $A$ is invertible, find $A^{-1}$.


In [6]:
# TODO: define the identity matrix and compute determinant and inverse
I = np.array([[1,0],[0,1]])
det_A = 1*4-3*2

if det_A != 0:
    A_inv = np.linalg.inv(A)
# print results for your reference
print("Inverted A is:",A_inv)

Inverted A is: [[-2.   1. ]
 [ 1.5 -0.5]]


### 5. Determinant & Geometry
Given $C = \begin{bmatrix}2 & 0 \\ 0 & 3\end{bmatrix}$:
1. Compute $\det(C)$.
2. Explain, in your own words, the geometric meaning of a determinant.


In [7]:
C = np.array([[2, 0], [0, 3]])

# TODO: compute the determinant numerically if desired
det_C = np.linalg.det(C)
print('det(C) =', det_C)


det(C) = 6.0


## Part C. Vector Spaces & Norms
Norms measure vector magnitude; orthogonality and projections capture geometric relationships.

### 6. Norms
For $x = [3, 4]$, compute:
1. $\lVert x \rVert_1$
2. $\lVert x \rVert_2$
3. $\lVert x \rVert_\infty$


In [9]:
x_vec = np.array([3, 4])

# TODO: compute the requested norms
l1 = np.linalg.norm(x_vec,1)
l2 = np.linalg.norm(x_vec,2)
linf = np.linalg.norm(x_vec,np.inf)
# print results here when ready

print(l1,l2,linf)


7.0 5.0 4.0


### 7. Orthogonality & Projection
With $u = [1, 0]$ and $v = [3, 4]$:
1. Test whether $u$ and $v$ are orthogonal.
2. Compute the projection of $v$ onto $u$.
Projection Formula:
$$
proj_{v}(u)=\frac{u\cdot v}{u\cdot u}u
$$


In [11]:
u = np.array([1, 0])
v = np.array([3, 4])

# TODO: compute u dot v and the projection expression
dot_uv = u@v

proj_v_on_u = ((u@v)/(u@u))*u
# print your conclusions
print(dot_uv,proj_v_on_u)


3 [3. 0.]


## Part D. Eigenvalues & Eigenvectors
Eigen decompositions help interpret linear transformations and power techniques like PCA.

### 8. Eigenvalues & Eigenvectors
For $A = \begin{bmatrix}2 & 0 \\ 0 & 3\end{bmatrix}$:
1. Find its eigenvalues.
2. For each eigenvalue, record one corresponding eigenvector.


In [13]:
A_diag = np.array([[2, 0], [0, 3]])

# TODO: compute eigenvalues and eigenvectors manually or with numpy.linalg.eig
eigvals, eigvecs = np.linalg.eig(A_diag)
print(eigvals)
print(eigvecs)


[2. 3.]
[[1. 0.]
 [0. 1.]]


### 9. Diagonalization
State whether the above matrix $A$ is diagonalizable and provide your reasoning.


## Part E. Applications in Deep Learning
Connect linear algebra back to neural network computations and dimensionality reduction.

### 10. Neural Network Layer
For input $x = [1, 2]$, weights $W = \begin{bmatrix}1 & -1 \\ 0 & 2\end{bmatrix}$, and bias $b = \begin{bmatrix}1 \\ 0\end{bmatrix}$, compute the layer output $y = Wx + b$.


In [14]:
x_input = np.array([1, 2])
W = np.array([[1, -1], [0, 2]])
b = np.array([1, 0])

# TODO: compute y
y = np.dot(W,x_input.transpose())+b
print('Layer output y =', y)


Layer output y = [0 4]


### 11. PCA Connection
Explain why eigenvalue decomposition is useful for dimensionality reduction techniques such as PCA. Provide an intuitive explanation in your own words.


## Reflection
Summarize the areas that felt most comfortable or challenging, and list any follow-up resources to consult.
