# 📘 NumPy `numpy.linalg` Knowledge Points and Exercises

Use this recap to solidify the key linear algebra utilities available in `numpy.linalg`.
Each section lists the concept, an exercise, and a starter code cell with preset data.
Complete the TODOs by implementing the computations yourself.


In [7]:
import numpy as np

from matplotlib import pyplot as plt
# All exercises below assume NumPy has been imported as np.


## 1. Norms (Vector and Matrix)

### Vector Norms
A **norm** measures the "size" of a vector $x \in \mathbb{R}^n$:

- **L1 norm**: $\|x\|_1 = \sum_{i=1}^n |x_i|$ (Manhattan distance)
- **L2 norm**: $\|x\|_2 = \sqrt{\sum_{i=1}^n |x_i|^2}$ (Euclidean distance)  
- **∞ norm**: $\|x\|_\infty = \max_i |x_i|$ (largest component)

### Matrix Norms
For matrix $A \in \mathbb{R}^{m \times n}$:

- **L1 norm**: $\|A\|_1 = \max_j \sum_i |a_{ij}|$ (max column sum)
- **L2 norm**: $\|A\|_2 = \sigma_{\max}(A)$ (largest singular value)
- **∞ norm**: $\|A\|_\infty = \max_i \sum_j |a_{ij}|$ (max row sum)
- **Frobenius norm**: $\|A\|_F = \sqrt{\sum_{i,j} a_{ij}^2}$ (L2 of all entries)

**Exercise**: Given $A = \begin{bmatrix}1 & -2 \\ 3 & 4\end{bmatrix}$ and vector $v = [3, -4, 12]$:
- Compute the Frobenius norm of $A$
- Compute the L2 norm of vector $v$

In [8]:
A = np.array([[1, -2], [3, 4]], dtype=float)
vector_v = np.array([3, -4, 12], dtype=float)

# Use np.linalg.norm to compute the requested norms
print("Frobenius norm of A:", np.linalg.norm(A, 'fro'))  # or just np.linalg.norm(A)
print("L2 norm of vector v:", np.linalg.norm(vector_v))

# Additional examples of different norms:
print("\n--- Matrix A norms ---")
print("L1 norm of A:", np.linalg.norm(A, ord=1))
print("L2 norm of A:", np.linalg.norm(A, ord=2))
print("∞ norm of A:", np.linalg.norm(A, ord=np.inf))

print("\n--- Vector v norms ---")  
print("L1 norm of v:", np.linalg.norm(vector_v, ord=1))
print("∞ norm of v:", np.linalg.norm(vector_v, ord=np.inf))

Frobenius norm of A: 5.477225575051661
L2 norm of vector v: 13.0

--- Matrix A norms ---
L1 norm of A: 6.0
L2 norm of A: 5.116672736016927
∞ norm of A: 7.0

--- Vector v norms ---
L1 norm of v: 19.0
∞ norm of v: 12.0


## 2. Determinant (`det`)

**Definition**: For square matrix $A \in \mathbb{R}^{n \times n}$, the determinant $\det(A)$ is a scalar.

**Key formulas**:
- $2 \times 2$: $\det\begin{bmatrix}a & b \\ c & d\end{bmatrix} = ad - bc$
- General: Laplace expansion along any row/column

**Geometric meaning**: $|\det(A)|$ = scaling factor for area (2D) or volume (3D) under transformation $A$.

**Properties**:
- $A$ is invertible ⟺ $\det(A) \neq 0$
- $\det(AB) = \det(A) \cdot \det(B)$
- If $\det(A) = 0$, rows/columns are linearly dependent

**Exercise**: Compute $\det(B)$ for $B = \begin{bmatrix}2 & 1 \\ 5 & 3\end{bmatrix}$ and determine if $B$ is invertible.

In [9]:
B = np.array([[2, 1], [5, 3]], dtype=float)

# Compute np.linalg.det(B) and interpret the result
det_B = np.linalg.det(B)
print(f"det(B) = {det_B}")

# Manual calculation: 2*3 - 1*5 = 6 - 5 = 1
print(f"Manual calculation: 2*3 - 1*5 = {2*3 - 1*5}")

# Invertibility check
if det_B != 0:
    print("B is invertible (det ≠ 0)")
else:
    print("B is singular (det = 0)")

det(B) = 1.0000000000000002
Manual calculation: 2*3 - 1*5 = 1
B is invertible (det ≠ 0)


## 3. Matrix Inverse (`inv`)

**Definition**: For square matrix $A$, the inverse $A^{-1}$ satisfies $A A^{-1} = A^{-1} A = I$.

**Existence**: $A^{-1}$ exists ⟺ $\det(A) \neq 0$ (non-singular matrix).

**Formula (2×2)**:
$$A = \begin{bmatrix} a & b \\ c & d \end{bmatrix} \Rightarrow A^{-1} = \frac{1}{ad-bc} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}$$

**Properties**:
- $(AB)^{-1} = B^{-1}A^{-1}$
- $(A^T)^{-1} = (A^{-1})^T$
- If $\det(A) = 0$, matrix is singular (no inverse)

**Exercise**: Find inverse of $C = \begin{bmatrix}4 & 7 \\ 2 & 6\end{bmatrix}$ and verify $C \cdot C^{-1} = I$.

In [10]:
C = np.array([[4, 7], [2, 6]], dtype=float)

# Compute C_inv = np.linalg.inv(C) and verify that C @ C_inv gives identity
C_inv = np.linalg.inv(C)
print("C_inv:\n", C_inv)

# Verify C @ C_inv = I
product = C @ C_inv
print("\nC @ C_inv:\n", product)

# Check if close to identity (accounting for floating point errors)
identity_check = np.allclose(product, np.eye(2))
print(f"\nIs C @ C_inv ≈ I? {identity_check}")

# Manual calculation for 2x2 inverse
det_C = np.linalg.det(C)
print(f"\ndet(C) = {det_C}")
print(f"Manual inverse: 1/{det_C} * [[6, -7], [-2, 4]]")

C_inv:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

C @ C_inv:
 [[ 1.00000000e+00 -1.11022302e-16]
 [-1.11022302e-16  1.00000000e+00]]

Is C @ C_inv ≈ I? True

det(C) = 10.000000000000002
Manual inverse: 1/10.000000000000002 * [[6, -7], [-2, 4]]


## 4. Solve Linear System (`solve`)

**Problem**: Solve $Ax = b$ for unknown vector $x$.

**System types**:
- **Square** ($m = n$): Unique solution if $\det(A) \neq 0$
- **Overdetermined** ($m > n$): More equations than unknowns → least squares
- **Underdetermined** ($m < n$): More unknowns than equations → infinite solutions

**Methods**:
- **Direct**: `np.linalg.solve(A, b)` (most efficient for square systems)
- **Matrix inverse**: $x = A^{-1}b$ (avoid for numerical stability)
- **Least squares**: `np.linalg.lstsq(A, b)` for overdetermined systems

**Exercise**: Solve the system:
$$\begin{cases} 2x + y = 5 \\ 4x - 6y = -2 \end{cases}$$

In [11]:
A_system = np.array([[2, 1], [4, -6]], dtype=float)
b_system = np.array([5, -2], dtype=float)

# Solve for the vector x that satisfies A_system @ x = b_system
x_solution = np.linalg.solve(A_system, b_system)
print("Solution x =", x_solution)

# Verify the solution
verification = A_system @ x_solution
print("Verification A @ x =", verification)
print("Original b =", b_system)
print("Match?", np.allclose(verification, b_system))

# Alternative: using matrix inverse (less efficient)
x_inverse = np.linalg.inv(A_system) @ b_system
print("\nUsing inverse: x =", x_inverse)
print("Same result?", np.allclose(x_solution, x_inverse))

Solution x = [1.75 1.5 ]
Verification A @ x = [ 5. -2.]
Original b = [ 5. -2.]
Match? True

Using inverse: x = [1.75 1.5 ]
Same result? True


## 5. Eigenvalues and Eigenvectors (`eig`)

**Definition**: For square matrix $A$, find $\lambda$ and $v \neq 0$ such that:
$$Av = \lambda v$$
- $\lambda$: eigenvalue (scaling factor)
- $v$: eigenvector (preserved direction)

**Geometric meaning**: Eigenvectors are special directions that $A$ only stretches/shrinks (no rotation).

**Characteristic equation**: $\det(A - \lambda I) = 0$

**Properties**:
- $n \times n$ matrix has at most $n$ eigenvalues
- $\text{trace}(A) = \sum \lambda_i$, $\det(A) = \prod \lambda_i$
- Symmetric matrices have real eigenvalues and orthogonal eigenvectors

**Applications**: PCA, stability analysis, Google PageRank, quantum mechanics

**Exercise**: Find eigenvalues and eigenvectors of $D = \begin{bmatrix}1 & 2 \\ 2 & 1\end{bmatrix}$.

In [12]:
D = np.array([[1, 2], [2, 1]], dtype=float)

# Use np.linalg.eig(D) to obtain eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(D)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

# Verify: A @ v = λ @ v for each eigenvalue/eigenvector pair
print("\n--- Verification ---")
for i in range(len(eigvals)):
    λ = eigvals[i]
    v = eigvecs[:, i]  # i-th column is i-th eigenvector
    
    Av = D @ v
    λv = λ * v
    
    print(f"λ{i+1} = {λ:.3f}")
    print(f"A @ v{i+1} = {Av}")
    print(f"λ{i+1} * v{i+1} = {λv}")
    print(f"Match? {np.allclose(Av, λv)}\n")

# Check properties: trace and determinant
print(f"trace(D) = {np.trace(D)}, sum(eigenvalues) = {np.sum(eigvals)}")
print(f"det(D) = {np.linalg.det(D)}, product(eigenvalues) = {np.prod(eigvals)}")

Eigenvalues: [ 3. -1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

--- Verification ---
λ1 = 3.000
A @ v1 = [2.12132034 2.12132034]
λ1 * v1 = [2.12132034 2.12132034]
Match? True

λ2 = -1.000
A @ v2 = [ 0.70710678 -0.70710678]
λ2 * v2 = [ 0.70710678 -0.70710678]
Match? True

trace(D) = 2.0, sum(eigenvalues) = 2.000000000000001
det(D) = -2.9999999999999996, product(eigenvalues) = -2.999999999999999



---

## 6. Singular Value Decomposition (`svd`)

- **Core idea:** Any matrix $A \in \mathbb{R}^{m \times n}$ factors as $A = U \Sigma V^T$ with orthogonal $U$ and $V$ and non-negative singular values on the diagonal of $\Sigma$.
- **Geometry:** $V^T$ applies a rotation/reflection to the input, $\Sigma$ rescales coordinate axes, and $U$ applies a rotation/reflection to the output—capturing how $A$ stretches vectors.
- **Useful facts:** singular values equal $\sqrt{\text{eigenvalues of }A^T A}$; the number of non-zero $\sigma_i$ gives $\operatorname{rank}(A)$; $\kappa(A) = \sigma_{\max}/\sigma_{\min}$; SVD exists for every real matrix.
- **Applications:** PCA (principal components), low-rank approximation, and diagnosing numerical stability in deep models.

**Exercise:** Perform SVD on
$$
E = \begin{bmatrix}3 & 1 \\ 1 & 3\end{bmatrix}
$$
and verify $E = U \Sigma V^T$.



In [13]:
E = np.array([[3, 1], [1, 3]], dtype=float)

# Compute U, S, Vt = np.linalg.svd(E) and verify the reconstruction
U, S, Vt = np.linalg.svd(E)
print("U (left singular vectors):\n", U)
print("\nS (singular values):", S)
print("\nVt (right singular vectors transposed):\n", Vt)

# Verify reconstruction: E = U @ diag(S) @ Vt
E_reconstructed = U @ np.diag(S) @ Vt
print("\nOriginal E:\n", E)
print("\nReconstructed E:\n", E_reconstructed)
print("\nReconstruction accurate?", np.allclose(E, E_reconstructed))

U (left singular vectors):
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

S (singular values): [4. 2.]

Vt (right singular vectors transposed):
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Original E:
 [[3. 1.]
 [1. 3.]]

Reconstructed E:
 [[3. 1.]
 [1. 3.]]

Reconstruction accurate? True



---

## 7. Matrix Rank (`matrix_rank`)

- **Definition:** Rank counts the number of linearly independent rows/columns; row rank equals column rank and cannot exceed $\min(m,n)$.
- **Geometry:** It is the dimension of the subspace spanned by the matrix—full-rank square matrices are invertible ($\det \neq 0$), lower rank means the map collapses dimensions.
- **How to compute:** Perform Gaussian elimination, count non-zero singular values (SVD), or call `np.linalg.matrix_rank`.
- **Why it matters:** Reveals independent equations in linear systems, the intrinsic dimensionality used in PCA/compression, and whether low-rank weights may restrict deep models.

**Exercise:** Find the rank of
$$
F = \begin{bmatrix}
1 & 2 & 3 \\
2 & 4 & 6 \\
3 & 6 & 9
\end{bmatrix}
$$
and explain the result.



In [14]:
F = np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]], dtype=float)

# Evaluate np.linalg.matrix_rank(F) and discuss why the rank has that value
rank_F = np.linalg.matrix_rank(F)
print(f"Matrix F:\n{F}")
print(f"\nRank of F: {rank_F}")

# Verify linear dependence
print(f"\nVerification:")
print(f"2 * row[0] = {2 * F[0]}")
print(f"row[1] = {F[1]}")
print(f"Are they equal? {np.allclose(2 * F[0], F[1])}")

print(f"\n3 * row[0] = {3 * F[0]}")
print(f"row[2] = {F[2]}")
print(f"Are they equal? {np.allclose(3 * F[0], F[2])}")

Matrix F:
[[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]]

Rank of F: 1

Verification:
2 * row[0] = [2. 4. 6.]
row[1] = [2. 4. 6.]
Are they equal? True

3 * row[0] = [3. 6. 9.]
row[2] = [3. 6. 9.]
Are they equal? True


**Explanation**: Because $2 \times F_0 = F_1$ and $3 \times F_0 = F_2$, both rows $F_1$ and $F_2$ are linearly dependent on $F_0$, so the rank is 1.

---

## 8. Pseudoinverse (`pinv`)

- **Concept**: Moore–Penrose pseudoinverse, used in underdetermined or overdetermined systems.
- **Exercise**:
  For
  $$
  G = \begin{bmatrix}1 & 2 \\ 3 & 4 \\ 5 & 6\end{bmatrix}
  $$
  compute the pseudoinverse and use it to solve the least squares problem $Gx \approx [7, 8, 9]^T$.



To solve $Gx = b$, we can calculate $G^+ \cdot b$, because:
$$
G^+ \cdot G \cdot x = G^+ \cdot b \\
I_n \cdot x = x
$$

In [15]:
G = np.array([[1, 2], [3, 4], [5, 6]], dtype=float)
b_ls = np.array([7, 8, 9], dtype=float)

# Compute the Moore–Penrose pseudoinverse of G and obtain the least-squares solution
G_pinv = np.linalg.pinv(G)
x_ls = G_pinv @ b_ls

print("Matrix G:\n", G)
print("\nPseudoinverse G+:\n", G_pinv)
print("\nLeast-squares solution x:", x_ls)

# Verify: G @ x should be as close to b as possible
Gx = G @ x_ls
print(f"\nG @ x = {Gx}")
print(f"Original b = {b_ls}")
print(f"Residual ||Gx - b|| = {np.linalg.norm(Gx - b_ls):.6f}")

Matrix G:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]

Pseudoinverse G+:
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]

Least-squares solution x: [-6.   6.5]

G @ x = [7. 8. 9.]
Original b = [7. 8. 9.]
Residual ||Gx - b|| = 0.000000


---

## 9. QR Decomposition (`qr`)

**Definition:** For $A\in\mathbb{R}^{m\times n}$ with $m\ge n$, factor $A=QR$ with column-orthonormal $Q\in\mathbb{R}^{m\times n}$ and upper-triangular $R\in\mathbb{R}^{n\times n}$. If $m=n$, $Q^TQ=I$.

**Geometry:** $Q$ re-expresses vectors in an orthonormal basis (rotation/reflection); $R$ applies the scaling/combination in that basis.

**Computation:** Classical Gram-Schmidt is instructive but unstable; NumPy uses Householder reflections or Givens rotations for robustness.

**Applications:**
- Solve $Ax=b$ via $QRx=b\Rightarrow Rx=Q^Tb$.
- Least-squares fits when $m>n$.
- Core step in QR eigenvalue algorithms and other numerically stable routines.

**Try it in NumPy:**

```python
import numpy as np
A = np.array([[1., 1.],
              [1., -1.],
              [1., 2.]])
Q, R = np.linalg.qr(A)
print(Q)
print(R)
print(np.allclose(A, Q @ R))
```



In [16]:
H = np.array([[1, 1], [1, -1]], dtype=float)
b_qr = np.array([2, 0], dtype=float)

# Compute the QR decomposition of H and use it to solve H @ x = b_qr
Q, R = np.linalg.qr(H)

print("Matrix H:\n", H)
print("\nQ (orthogonal matrix):\n", Q)
print("\nR (upper triangular matrix):\n", R)

# Verify QR decomposition: H = Q @ R
print(f"\nVerification: H = Q @ R")
print(f"Q @ R =\n{Q @ R}")
print(f"Reconstruction accurate? {np.allclose(H, Q @ R)}")

# Solve using QR: H @ x = b => Q @ R @ x = b => R @ x = Q^T @ b
x_qr = np.linalg.solve(R, Q.T @ b_qr)
print(f"\nSolution x = {x_qr}")

# Verify solution
verification = H @ x_qr
print(f"H @ x = {verification}")
print(f"Original b = {b_qr}")
print(f"Solution correct? {np.allclose(verification, b_qr)}")

Matrix H:
 [[ 1.  1.]
 [ 1. -1.]]

Q (orthogonal matrix):
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

R (upper triangular matrix):
 [[-1.41421356e+00  3.33066907e-16]
 [ 0.00000000e+00 -1.41421356e+00]]

Verification: H = Q @ R
Q @ R =
[[ 1.  1.]
 [ 1. -1.]]
Reconstruction accurate? True

Solution x = [1. 1.]
H @ x = [ 2.00000000e+00 -1.11022302e-16]
Original b = [2. 0.]
Solution correct? True
