# Lecture 4 Exercises: LU Decomposition

Hands-on practice with **A = LU** factorization.

In [ ]:
import numpy as np

print("✓ Libraries imported successfully")

---

## Exercise 1: Manual LU Decomposition (2×2)

Compute the LU decomposition of $A = \begin{bmatrix} 2 & 3 \\ 4 & 7 \end{bmatrix}$ by hand.

**Steps:**
1. Perform elimination to get $U$
2. Record the multiplier $m_{21}$ to build $L$
3. Verify $A = LU$

In [14]:
# Original matrix
A = np.array([[2, 3],
              [4, 7]])

print("Original matrix A:")
print(A)
print()

# TODO: Compute multiplier m21
m21 = 4/2  # Fill this in

# TODO: Build L matrix
L = np.array([[1, 0],
              [m21, 1]])  # Fill this in

# TODO: Build U matrix (result after elimination)
U = np.array([[2, 3],
              [0, 1]])  # Fill this in

print(f"Multiplier m21 = {m21}")
print(f"\nL matrix:\n{L}")
print(f"\nU matrix:\n{U}")
print(f"\nVerification - LU:\n{L @ U}")
print(f"\nA = LU? {np.allclose(A, L @ U)}")

Original matrix A:
[[2 3]
 [4 7]]

Multiplier m21 = 2.0

L matrix:
[[1. 0.]
 [2. 1.]]

U matrix:
[[2 3]
 [0 1]]

Verification - LU:
[[2. 3.]
 [4. 7.]]

A = LU? True


### Solution

In [15]:
# Solution
m21 = 4 / 2  # = 2

L = np.array([[1, 0],
              [m21, 1]])

# After eliminating: row2 - 2*row1
# [2, 3]        [2, 3]
# [4, 7]  -->   [0, 1]  (7 - 2*3 = 1)
U = np.array([[2, 3],
              [0, 1]])

print(f"L =\n{L}")
print(f"\nU =\n{U}")
print(f"\nLU =\n{L @ U}")
print(f"\nVerified: {np.allclose(A, L @ U)}")

L =
[[1. 0.]
 [2. 1.]]

U =
[[2 3]
 [0 1]]

LU =
[[2. 3.]
 [4. 7.]]

Verified: True


---

## Exercise 2: LU Decomposition (3×3)

Perform LU decomposition on:

$$
A = \begin{bmatrix} 2 & 1 & 1 \\ 4 & -6 & 0 \\ -2 & 7 & 2 \end{bmatrix}
$$

**Goal:** Find $L$ and $U$ such that $A = LU$

In [16]:
A = np.array([[2, 1, 1],
              [4, -6, 0],
              [-2, 7, 2]])

print("Original A:")
print(A)
print()

# Manual elimination step-by-step
print("Step 1: Eliminate column 1")
print("-" * 40)

# TODO: Calculate multipliers
m21 = 4/2  # Multiplier for row 2
m31 = -2/2  # Multiplier for row 3

print(f"m21 = {m21}")
print(f"m31 = {m31}")

# TODO: Create A1 after first elimination
A1 = A.copy().astype(float)
A1[1] = A1[1] - m21 * A1[0]  # Update row 2
A1[2] = A1[2] - m31 * A1[0]  # Update row 3

print(f"\nAfter eliminating column 1:\n{A1}")
print()

print("Step 2: Eliminate column 2")
print("-" * 40)

# TODO: Calculate multiplier
m32 = 8/-8  # Multiplier for row 3

print(f"m32 = {m32}")

# TODO: Create U (final upper triangular)
U = A1.copy()
U[2] = U[2] - m32 * U[1]  # Update row 3

print(f"\nU (upper triangular):\n{U}")
print()

# TODO: Build L from multipliers
L = np.array([[1, 0, 0],
              [m21, 1, 0],
              [m31, m32, 1]])

print(f"L (lower triangular):\n{L}")
print()

# Verify
print(f"LU =\n{L @ U}")
print(f"\nA = LU? {np.allclose(A, L @ U)}")

Original A:
[[ 2  1  1]
 [ 4 -6  0]
 [-2  7  2]]

Step 1: Eliminate column 1
----------------------------------------
m21 = 2.0
m31 = -1.0

After eliminating column 1:
[[ 2.  1.  1.]
 [ 0. -8. -2.]
 [ 0.  8.  3.]]

Step 2: Eliminate column 2
----------------------------------------
m32 = -1.0

U (upper triangular):
[[ 2.  1.  1.]
 [ 0. -8. -2.]
 [ 0.  0.  1.]]

L (lower triangular):
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1. -1.  1.]]

LU =
[[ 2.  1.  1.]
 [ 4. -6.  0.]
 [-2.  7.  2.]]

A = LU? True


### Solution

In [17]:
# Solution
A = np.array([[2, 1, 1],
              [4, -6, 0],
              [-2, 7, 2]], dtype=float)

print("Step-by-step elimination:\n")

# Step 1: Eliminate column 1
m21 = A[1, 0] / A[0, 0]  # 4/2 = 2
m31 = A[2, 0] / A[0, 0]  # -2/2 = -1

A1 = A.copy()
A1[1] = A1[1] - m21 * A1[0]  # row2 - 2*row1
A1[2] = A1[2] - m31 * A1[0]  # row3 - (-1)*row1

print(f"m21 = {m21}, m31 = {m31}")
print(f"After step 1:\n{A1}\n")

# Step 2: Eliminate column 2
m32 = A1[2, 1] / A1[1, 1]  # 8/(-8) = -1

U = A1.copy()
U[2] = U[2] - m32 * U[1]  # row3 - (-1)*row2

print(f"m32 = {m32}")
print(f"U (final):\n{U}\n")

# Build L
L = np.array([[1, 0, 0],
              [m21, 1, 0],
              [m31, m32, 1]])

print(f"L:\n{L}\n")
print(f"Verification: LU =\n{L @ U}")
print(f"\nA = LU? {np.allclose(A, L @ U)}")

Step-by-step elimination:

m21 = 2.0, m31 = -1.0
After step 1:
[[ 2.  1.  1.]
 [ 0. -8. -2.]
 [ 0.  8.  3.]]

m32 = -1.0
U (final):
[[ 2.  1.  1.]
 [ 0. -8. -2.]
 [ 0.  0.  1.]]

L:
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1. -1.  1.]]

Verification: LU =
[[ 2.  1.  1.]
 [ 4. -6.  0.]
 [-2.  7.  2.]]

A = LU? True


---

## Summary

### What You Practiced

1. ✅ **Manual LU decomposition** for 2×2 and 3×3 matrices
2. ✅ **Recording multipliers** to build $L$
3. ✅ **Verification** that $A = LU$

### Key Formulas

- **LU decomposition:** $A = LU$
- **Multiplier:** $m_{ij} = \frac{A_{ij}}{\text{pivot at } (j,j)}$
- **L structure:** Multipliers fill in below the diagonal, 1's on diagonal
- **U structure:** Result of elimination (upper triangular)

**Next:** Practice with more advanced topics in later lectures!